import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./components/sub-components/navbar";
import Footer from "./components/sub-components/footer";
import { playfair } from "./font";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${playfair.className}`}>
      <body>
        <NavBar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
